<?php

namespace Jan\MOCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MOCPlayerInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MOCPlayerInstanceRepository extends EntityRepository
{
}
